### ISSUE TITLE
AS5047P内部是存在LDO的 为什么还要单独设计一个RT9193的电路呢

### ISSUE THREAD

**Issue by UPUPGOO** [Ncerzzk/encoder_as5040#1]
如题

**Comment by Ncerzzk** [comment]
当时设计时希望能支持5V供电与3V3供电
如果使用5V供电，且无片外LDO，则是5V operation mode，as5047在这种模式下的VIH(min)=0.7*VDD=3.5V，3V3供电的单片机难以满足此电平（可能需要OD上拉等其他方式辅助）
